-- Grant warehouse usage to DATAIKU_ROLE
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DATAIKU_ROLE;

-- Grant all permissions on ATP_INSIGHTS database to DATAIKU_ROLE
GRANT USAGE ON DATABASE ATP_INSIGHTS TO ROLE DATAIKU_ROLE;

-- Grant all permissions on DEFAULT schema to DATAIKU_ROLE
GRANT USAGE ON SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;


-- Grant privileges on all existing tables in the schema
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;

-- Grant privileges on all existing views in the schema
GRANT SELECT ON ALL VIEWS IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;

-- Grant privileges on future tables and views (for objects created later)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;

-- Grant privileges on stages
GRANT USAGE ON ALL STAGES IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUTURE STAGES IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;

-- Grant privileges on functions and procedures
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;

-- Grant privileges on dynamic tables
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA ATP_INSIGHTS.DEFAULT TO ROLE DATAIKU_ROLE;
