
CREATE OR REPLACE CORTEX SEARCH SERVICE PC_DATAIKU_DB.PUBLIC.ATP_CORTEX_SEARCH
ON MATCH_SUMMARY
ATTRIBUTES MATCH_ROUND, TOURNAMENT_NAME, TOURNAMENT_LEVEL
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '1 day'
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS (
	SELECT
		MATCH_SUMMARY,
		MATCH_ROUND,
		TOURNAMENT_NAME,
		TOURNAMENT_LEVEL,
		TOURNAMENT_SURFACE,
		TOURNAMENT_LEAGUE
	FROM PC_DATAIKU_DB.PUBLIC.MATCHES_SAMPLE_100_ENRICHED
);

-- Grant USAGE on the Cortex Search Service
GRANT USAGE ON CORTEX SEARCH SERVICE PC_DATAIKU_DB.PUBLIC.ATP_CORTEX_SEARCH TO ROLE PC_DATAIKU_ROLE;
