
CREATE OR REPLACE CORTEX SEARCH SERVICE ATP_INSIGHTS.DEFAULT.ATP_CORTEX_SEARCH
ON MATCH_SUMMARY
ATTRIBUTES MATCH_ROUND, TOURNAMENT_NAME, TOURNAMENT_LEVEL
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '1 day'
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
AS (
	SELECT
		MATCH_SUMMARY,
		MATCH_ROUND,
		TOURNAMENT_NAME,
		TOURNAMENT_LEVEL,
		TOURNAMENT_SURFACE,
		TOURNAMENT_LEAGUE
	FROM ATP_INSIGHTS.DEFAULT.MATCHES_ENRICHED
);

-- Grant USAGE on the Cortex Search Service
GRANT USAGE ON CORTEX SEARCH SERVICE ATP_INSIGHTS.DEFAULT.ATP_CORTEX_SEARCH TO ROLE DATAIKU_ROLE;
